name: Build templates and upload to blob

on:
  workflow_dispatch:
  schedule:
    - cron: '0,10,20,30,40,50,50 * * * *'
  push:
    branches:
      - "main"
    paths:
      - "templates/*/autopick*.png"
      - "templates/*/canvas*.png"
      - "templates/*/endu*.png"
      - "templates/*/endu_template.json"
      - "templates/*/mask*.png"
      - "templates/*/template.json"
      - "templates/*/version.txt"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        lfs: true
        
    - name: Python setup for template build
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Build templates
      run: |
        python3 -m pip install --upgrade pip
        if [ -f ./.build/template_assembler/requirements.txt ]; then pip install -r ./.build/template_assembler/requirements.txt; fi
        buildTemplates="mlp mlp_alliance mlp_world" # "mlp r-ainbowroad spain"
        for buildTemplate in $buildTemplates; do
            python3 .build/template_assembler/assemble_template.py templates/$buildTemplate
        done
    
    - name: Copy canvas files
      run: |
        mkdir -p ./dist
        copyTemplates="mlp mlp_alliance mlp_world r-ainbowroad spain phoenixmc"
        # cp -f ./templates/mlp/autopick.png ./templates/mlp/canvas.png ./templates/mlp/mask.png ./templates/mlp/endu.png ./templates/mlp/endu_template.json ./templates/mlp/version.txt ./dist/mlp
        for copyTemplate in $copyTemplates; do
            mkdir -p ./dist/$copyTemplate
            for copyFile in autopick.png canvas.png mask.png version.txt; do
                echo "Checking ./templates/$copyTemplate/$copyFile"
                if [[ -f ./templates/$copyTemplate/$copyFile ]]; then
                    cp -f ./templates/$copyTemplate/$copyFile ./dist/$copyTemplate
                fi
            done
            for copyFile in `ls -1 ./templates/$copyTemplate/endu*`; do
                echo "Checking $copyFile"
                if [[ -f $copyFile ]]; then
                    cp -f $copyFile ./dist/$copyTemplate
                fi
            done
        done

    - name: Produce build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: |
          dist

    # creds will expire around 2024-06-16
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.PONYPLACE_BLOB_CREDS }}
    
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ponyplace --auth-mode login -d '$web' --overwrite true -s ./dist
    
    - name: Azure logout
      run: az logout
      if: always()
